import Vue from 'vue'
import { Button, NavBar, Icon, Form, Field, Toast, Popover, Grid, GridItem, Card, Search, Collapse, CollapseItem, Row, Col, Tag, Dialog, SwipeCell } from 'vant'

Vue.use(Button)
Vue.use(NavBar)
Vue.use(Icon)
Vue.use(Form)
Vue.use(Field)
Vue.use(Popover)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Card)
Vue.use(Search)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tag)
Vue.use(SwipeCell)
Vue.use(Toast)
Vue.use(Dialog)